### ISSUE TITLE
This file was placed in vivado and The logic synthesis time is too long

### ISSUE THREAD

**Issue by wxbbuaa2011** [stremovsky/moneroasic#1]
synthesis time is about three hours in a servers. How to solve it?

**Comment by stremovsky** [comment]
Hello.

Most of the time I ran this code in simulation.

To be able to synthesize the code on FPGA you need to have expensive boards, probably starting from $ 1000.

Another option is to decrease memory size requirements from 2MB to for example 16kb (in this case you will not get the requests you expect as you decrease big buffer size).

You will need to change the **RAM_DEPTH** parameter of cryptonight() function. 

Best of luck,
Yuli

**Comment by wxbbuaa2011** [comment]
Thank you very much for your reply. This algorithm is somewhat different from the introduction of an algorithm. So now I don't know that it is the most correct algorithm. I hope you understand the confusion of a novice. Thank you

At 2018-04-01 15:36:01, "Yuli" <notifications@github.com> wrote:


Hello.

Most of the time I ran this code in simulation.

To be able to synthesize the code on FPGA you need to have expensive boards, probably starting from $ 1000.

Another option is to decrease memory size requirements from 2MB to 16kb (in this case you will not get the requests you expect as you decrease big buffer size).

You will need to change the RAM_DEPTH parameter of cryptonight() function.

Best of luck,
Yuli

**Comment by wxbbuaa2011** [comment]
Thank you very much for your reply. This algorithm is somewhat different from the introduction of an algorithm（https://github.com/deepwn/deepMiner/blob/master/CryptoNight_CN.md）. So now I don't know that it is the most correct algorithm. I hope you understand the confusion of a novice. Thank you

At 2018-04-01 15:36:01, "Yuli" <notifications@github.com> wrote:


Hello.

Most of the time I ran this code in simulation.

To be able to synthesize the code on FPGA you need to have expensive boards, probably starting from $ 1000.

Another option is to decrease memory size requirements from 2MB to 16kb (in this case you will not get the requests you expect as you decrease big buffer size).

You will need to change the RAM_DEPTH parameter of cryptonight() function.

Best of luck,
Yuli

**Comment by stremovsky** [comment]
我的中文不太好

I used this code as referrent: https://github.com/xmrig/xmrig/blob/master/src/crypto/CryptoNight_x86.h

**Comment by wxbbuaa2011** [comment]
Thank you very much

在 2018-04-05 18:44:06，"Yuli" <notifications@github.com> 写道：


我的中文不太好

I used this code as referrent: https://github.com/xmrig/xmrig/blob/master/src/crypto/CryptoNight_x86.h
