### ISSUE TITLE
Can we publish the old commissioned article about SQL Injections?

### ISSUE THREAD

**Issue by shlomif** [stremovsky/moneroasic#3]
Hi @stremovsky ! If you remember, you commissioned me to write that article for the Green SQL site. I need your permission to publish it (under your choice of licence - see https://www.shlomifish.org/meta/copyrights/ ), as it is currently hosted in a private bitbucket hg repo - see https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket ). From what I recall, you paid me for writing it, so no problem there, but I still wish to have it published. Thanks!

**Comment by stremovsky** [comment]
Hi,

yes, no problems, you can publish it on your blog.

**Comment by shlomif** [comment]
@stremovsky : hi! Thanks for returning to me. 1. Which licence do you put it on? 2. Which blog? https://www.shlomifish.org/me/blogs/ . Thanks!

**Comment by stremovsky** [comment]
You can publish where you want and use any license.

**Comment by shlomif** [comment]
On Mon, 23 Mar 2020 08:15:00 -0700
Yuli <notifications@github.com> wrote:

> You can publish where you want and use any license.
> 

Thanks, Yuli!

-- 

Shlomi Fish       https://www.shlomifish.org/
https://www.shlomifish.org/humour/bits/facts/Summer-Glau/

Right to bear arms? In Soviet Russia, we have right to whole bear.
    — http://is.gd/EU4puV

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by shlomif** [comment]
Just for the record, I published it here for now: https://github.com/shlomif/SQL-Injections--danger-and-prevention . Thanks! Resolving.
